# Generated by Django 2.2.8 on 2020-10-21 22:05

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20201020_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
