# Generated by Django 2.2.8 on 2020-10-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20201022_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
