# Generated by Django 2.2.8 on 2020-12-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_remove_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
